In [3]:
import torch
from mc3d_trecsim import gmm
import numpy as np

r1 = 2  # Create uniform random numbers in half-open interval [2.0, 5.0)
r2 = 5

A = torch.randn(10, 3)

print('A:', A)
prod = torch.randn(5, 10).mm(A)
print('prod:', prod)
print('log:', torch.sum(prod, dim=-1))
print('log sum:', prod.log().sum())

A: tensor([[ 1.8879, -1.5269,  0.7961],
        [-0.9332,  0.3897,  1.4183],
        [-1.3538, -0.3013,  0.3844],
        [-0.3992,  1.1333,  0.2167],
        [ 0.0718,  0.4613, -0.5541],
        [ 0.8007, -0.1479, -0.7818],
        [ 1.7405, -0.1223, -0.0193],
        [-0.3815, -1.9333, -0.0846],
        [ 2.7684,  0.2992,  0.9723],
        [ 0.8147, -1.4238,  0.7372]])
prod: tensor([[-8.8850,  6.8566,  1.4809],
        [-2.1176,  0.8018,  0.6439],
        [ 1.3218,  4.7081, -3.3949],
        [-5.5193,  3.1697,  0.9428],
        [-0.4590,  2.0809, -1.3975]])
log: tensor([[    nan,  1.9252,  0.3927],
        [    nan, -0.2208, -0.4402],
        [ 0.2790,  1.5493,     nan],
        [    nan,  1.1536, -0.0589],
        [    nan,  0.7328,     nan]])
log sum: tensor(nan)


In [ ]:
from scipy.interpolate import BSpline
import numpy as np

k = 3
t = [1, 1, 1, 1, 2, 3, 3, 3, 3]
x = np.linspace(1.0, 3.0, 10)

design_matrix = BSpline.design_matrix(x, t, k).toarray()

print(design_matrix)

In [60]:
import numpy as np
from scipy.stats import multivariate_normal
np.set_printoptions(precision=12)

mean = np.random.uniform(0, 1, 3).round(4)
cov = np.random.uniform(0, 1, 9).reshape(3, 3).round(4)
p = np.random.uniform(0, 1, 3).round(4)

print('mean:', mean)
print('cov:', cov)
print('p:', p)

rv = multivariate_normal(mean, cov)
print('pdf:', rv.pdf(p))

mean: [0.5887 0.9628 0.0169]
cov: [[0.6965 0.8137 0.5098]
 [0.334  0.7908 0.0972]
 [0.442  0.52   0.694 ]]
p: [0.0909 0.2278 0.4103]
pdf: 0.02299078054645225


In [ ]:
import numpy as np
from scipy.stats import multivariate_normal
np.set_printoptions(precision=12)

mean = np.zeros((3, ))
cov = np.eye(3)
p = np.zeros((3, ))

print('mean:', mean)
print('cov:', cov)
print('p:', p)

rv = multivariate_normal(mean, cov)
print('pdf:', rv.pdf(p))

In [66]:
A = torch.from_numpy(np.array([[1.1e+03, 0.0, 9.2e+02],
                              [0.0, 1.1e+03, 5.8e+02],
                              [0.0, 0.0, 1.0]]))

P = torch.from_numpy(np.array([[4.8e-01, -4.5e-01, 7.4e-01, -3.8e+02],
                              [4.7e-01, 8.5e-01, 2.0e-01, -1.2e+02],
                              [-7.2e-01, 2.5e-01, 6.3e-01, 1.7e+02],
                              [0.0, 0.0, 0.0, 1.0]]))

RT = P[0:3,0:3].transpose(0, 1)
t = P[0:3, 3].reshape(3, 1)
torch.set_printoptions(precision=15)

P = torch.from_numpy(np.array([100.0, -200.0, 150.0]).reshape((3, 1)))
P.requires_grad_(True)

PC = RT.mm(P - t)

p = A.mm(PC / PC[2])[0:2, 0:1]

print("p:", p)

p[0,0].backward(retain_graph=True)
print("P:", P)
print("P.grad():", P.grad)
P.grad.zero_()

p[1,0].backward()
print("P:", P)
print("P.grad():", P.grad)
P.grad.zero_()

p: tensor([[1617.856705450091795],
        [-393.361910593998914]], dtype=torch.float64, grad_fn=<SliceBackward0>)
P: tensor([[ 100.],
        [-200.],
        [ 150.]], dtype=torch.float64, requires_grad=True)
P.grad(): tensor([[ 0.035474702899363],
        [ 1.155629696601291],
        [-3.771125916820447]], dtype=torch.float64)
P: tensor([[ 100.],
        [-200.],
        [ 150.]], dtype=torch.float64, requires_grad=True)
P.grad(): tensor([[0.689797347947211],
        [3.458886656824250],
        [2.719589723436067]], dtype=torch.float64)


tensor([[0.],
        [0.],
        [0.]], dtype=torch.float64)

In [4]:
torch.s
A = torch.randn(4, 4)

print(A.index())

tensor([[ 1.9678, -0.4572, -0.6060, -1.0111],
        [ 0.1902,  1.4594, -0.8258, -0.1915],
        [ 2.3175, -1.0404, -0.2979,  0.9873],
        [-1.6515,  0.2593, -0.0541,  0.1386]])
