In [6]:
import torch
from mc3d_trecsim import gmm
import numpy as np

A = torch.randn(3, 4, 5)

print(gmm.tensor(A))

tensor([[[ 0.1221, -1.0560, -0.5020,  1.1114, -3.4796],
         [ 0.7364, -0.5333,  1.7924, -0.9335,  0.2933],
         [ 0.7361, -0.7160,  1.3635, -0.4538, -0.4683],
         [ 1.0847, -1.5048,  1.3096, -0.9468,  0.9267]],

        [[ 0.5660, -0.1601, -0.3559,  1.8003, -0.3150],
         [ 0.3566, -0.7273,  1.6603,  0.8629, -0.1206],
         [ 0.4249,  0.4684, -1.4583,  0.4216,  0.2878],
         [-1.0934, -0.3034, -0.1292,  0.4850,  0.4113]],

        [[ 1.0589,  0.9670,  2.7312,  0.1818,  1.9472],
         [ 0.5652,  1.9477,  0.9613,  1.4542, -0.2582],
         [ 0.6031, -1.5415, -2.2331, -2.2128, -0.1277],
         [ 0.4579, -2.1632, -2.1209,  1.2213, -1.8697]]])


In [66]:
A = torch.from_numpy(np.array([[1.1e+03, 0.0, 9.2e+02],
                              [0.0, 1.1e+03, 5.8e+02],
                              [0.0, 0.0, 1.0]]))

P = torch.from_numpy(np.array([[4.8e-01, -4.5e-01, 7.4e-01, -3.8e+02],
                              [4.7e-01, 8.5e-01, 2.0e-01, -1.2e+02],
                              [-7.2e-01, 2.5e-01, 6.3e-01, 1.7e+02],
                              [0.0, 0.0, 0.0, 1.0]]))

RT = P[0:3,0:3].transpose(0, 1)
t = P[0:3, 3].reshape(3, 1)
torch.set_printoptions(precision=15)

P = torch.from_numpy(np.array([100.0, -200.0, 150.0]).reshape((3, 1)))
P.requires_grad_(True)

PC = RT.mm(P - t)

p = A.mm(PC / PC[2])[0:2, 0:1]

print("p:", p)

p[0,0].backward(retain_graph=True)
print("P:", P)
print("P.grad():", P.grad)
P.grad.zero_()

p[1,0].backward()
print("P:", P)
print("P.grad():", P.grad)
P.grad.zero_()

p: tensor([[1617.856705450091795],
        [-393.361910593998914]], dtype=torch.float64, grad_fn=<SliceBackward0>)
P: tensor([[ 100.],
        [-200.],
        [ 150.]], dtype=torch.float64, requires_grad=True)
P.grad(): tensor([[ 0.035474702899363],
        [ 1.155629696601291],
        [-3.771125916820447]], dtype=torch.float64)
P: tensor([[ 100.],
        [-200.],
        [ 150.]], dtype=torch.float64, requires_grad=True)
P.grad(): tensor([[0.689797347947211],
        [3.458886656824250],
        [2.719589723436067]], dtype=torch.float64)


tensor([[0.],
        [0.],
        [0.]], dtype=torch.float64)

In [4]:
torch.s
A = torch.randn(4, 4)

print(A.index())

tensor([[ 1.9678, -0.4572, -0.6060, -1.0111],
        [ 0.1902,  1.4594, -0.8258, -0.1915],
        [ 2.3175, -1.0404, -0.2979,  0.9873],
        [-1.6515,  0.2593, -0.0541,  0.1386]])
